### ISSUE TITLE
Need Help in time complexity 

### ISSUE THREAD

**Issue by arnabs542** [snehasishroy/leetcode-practice#1]
https://github.com/snehasishroy/leetcode-practice/blob/1ff132862a01d6fccb7ece9d547b8c761c3332da/src/main/java/CheapestFlightWithinKStop.java#L85

@snehasishroy can you tell the time complexity of dijkstra optimized and bfs version ?

**Comment by snehasishroy** [comment]
Hi,

Thank you for raising this question. 
Sure, I would love to tackle this problem.
In order to visualize the time complexity of optimized Dijkstra , you need to ask how many nodes can be pushed into the PriorityQueue. Normally Dijkstra visits each vertex only once and the time complexity is ElogV, e is the number of edges and v is the number of vertices.
Here, how many times a single vertex can be pushed to the queue, it can be approximately k times and how many times you are visiting an edge, again approximately k times. so it comes to EK * LOG(KV)

For BFS it's a bit complicated as we are iterating the entire graph. How many paths possible from each node? k paths.
So there are n^k combinations available.

Hope this helps. It's a bit complicated.

**Comment by arnabs542** [comment]
Thanks a lot.  
Have one more question. Why is the bfs one not giving tle as its exponential ?

**Comment by snehasishroy** [comment]
BFS is not giving TLE due to combination of pruning and weak test cases.
Space complexity of dijkstra would be higher than O(v) because each vertex is pushed multiple times in the priority queue. If you approximate the times to be K, then it would be O(kv)

**Comment by arnabs542** [comment]
Thanks a lot for helping me out.
