### ISSUE TITLE
time complexity query 

### ISSUE THREAD

**Issue by arnabs542** [snehasishroy/leetcode-practice#2]
https://github.com/snehasishroy/leetcode-practice/blob/b77e4a275de4da200b7ff05a7de5415d1ad6cf8b/src/main/java/ShortestSubarrayWithSumAtLeastK.java#L112
hi @snehasishroy what should be the time complexity of approach 3 binary search ? will it be O(n2) or O(nlogn) ?
thanks in advance

**Comment by snehasishroy** [comment]
It's going to be more than nlogn and less than n^2.
Because we keep on removing elements from the prefix sum, so we won't be seeing it again. If we won't have deleted it, then it would have been n^2 and it would have timed out.

It's more than nlogn because of repeated removal and `floor()` lookup which is logn per operation. 
Not really sure about the exact time complexity. It's a bit tricky.

Hope that helps.

**Comment by arnabs542** [comment]
thanks a lot for helping
